routes/web.php
<?php

use App\Http\Controllers\LogsController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\SalesOrderController;
use App\Http\Controllers\PurchaseOrderController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::prefix('dashboard')->middleware('auth:web')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard.index');
    Route::get('dailychart', [DashboardController::class, 'dailyChart'])->name('dashboard.chart.daily');
    Route::get('prosentasechart', [DashboardController::class, 'prosentaseChart'])->name('dashboard.chart.prosentase');
    Route::get('lastsixmonth', [DashboardController::class, 'sixMonthChartTransaction'])->name('dashboard.chart.sixmonth');
    Route::get('logs', [LogsController::class, 'index'])->name('logs.index');
    Route::get('/report/profit', [ReportController::class, 'profit'])->name('report.profit');
    Route::get('/report/stockcard', [ReportController::class, 'stockCard'])->name('report.stock-card');
    Route::get('/report/transaction', [ReportController::class, 'transaction'])->name('report.transaction');

    Route::resource('purchases', PurchaseOrderController::class)->except(['destroy']);
    Route::delete('purchases/destroy', [PurchaseOrderController::class, 'destroy'])->name('purchases.destroy');
    Route::post('purchase/upload-import', [PurchaseOrderController::class, 'uploadImport'])->name('purchases.upload.import');
    Route::post('purchase/execute-import', [PurchaseOrderController::class, 'executeImport'])->name('purchases.execute.import');
    
    Route::resource('sales', SalesOrderController::class)->except(['destroy']);
    Route::delete('sales/destroy', [SalesOrderController::class, 'destroy'])->name('sales.destroy');
    Route::post('sales/upload-import', [SalesOrderController::class, 'uploadImport'])->name('sales.upload.import');
    Route::post('sales/execute-import', [SalesOrderController::class, 'executeImport'])->name('sales.execute.import');
    
    Route::resource('products', ProductController::class);
    Route::post('producsts/stock-card', [ProductController::class, 'stockCard'])->name('products.stock-card');
    
});

Route::get('/send', function () {
    broadcast(new App\Events\EveryoneEvent());
    return response('Sent');
});

Route::get('/receiver', function () {
    return view('receiver');
});

require __DIR__.'/auth.php';

resources/views/partials/navbar.blade.php
<nav class="navbar  navbar-expand-lg navbar-dark bg-primary mb-4">
    <div class="container">
        <a class="navbar-brand" href="{{ route('dashboard.index') }}">Ecommerce Computer</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                @can('purchasing')
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('products.index') }}">
                        Produk
                    </a>
                </li>
                @endcan
                
                @can('sales')
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('sales.index') }}">
                        Penjualan
                    </a>
                </li>
                @endcan
                @can('purchasing')
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('purchases.index') }}">
                        Pembelian
                    </a>
                </li>
                @endcan
                @can('logs', 'report_transaction')
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Laporan
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ route('report.profit') }}">Laporan Laba </a>
                        <a class="dropdown-item" href="{{ route('report.transaction') }}">Laporan Transaksi</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{{ route('report.stock-card') }}">Kartu Stock</a>
                    </div>
                </li>
                @endcan
                <li class="nav-item active dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ auth()->user()->name }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        
                <form method="POST" action="{{ route('logout') }}">
                    <li class="dropdown-item">
                    @csrf
                    <a href="#" onclick="event.preventDefault();
                                                                    this.closest('form').submit();">
                        {{ __('Log out') }}
                    </a>

                    </li>
                </form>
        </div>
        </li>
        </ul>
    </div>
    </div>
</nav>