routes/web.php
<?php

use App\Http\Controllers\LogsController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\SalesOrderController;
use App\Http\Controllers\PurchaseOrderController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::prefix('dashboard')->middleware('auth:web')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard.index');
    Route::get('dailychart', [DashboardController::class, 'dailyChart'])->name('dashboard.chart.daily');
    Route::get('prosentasechart', [DashboardController::class, 'prosentaseChart'])->name('dashboard.chart.prosentase');
    Route::get('lastsixmonth', [DashboardController::class, 'sixMonthChartTransaction'])->name('dashboard.chart.sixmonth');
    Route::get('logs', [LogsController::class, 'index'])->name('logs.index');
    Route::get('/report/profit', [ReportController::class, 'profit'])->name('report.profit');
    Route::get('/report/stockcard', [ReportController::class, 'stockCard'])->name('report.stock-card');
    Route::get('/report/transaction', [ReportController::class, 'transaction'])->name('report.transaction');

    Route::resource('purchases', PurchaseOrderController::class)->except(['destroy']);
    Route::delete('purchases/destroy', [PurchaseOrderController::class, 'destroy'])->name('purchases.destroy');
    Route::post('purchase/upload-import', [PurchaseOrderController::class, 'uploadImport'])->name('purchases.upload.import');
    Route::post('purchase/execute-import', [PurchaseOrderController::class, 'executeImport'])->name('purchases.execute.import');
    
    Route::resource('sales', SalesOrderController::class)->except(['destroy']);
    Route::delete('sales/destroy', [SalesOrderController::class, 'destroy'])->name('sales.destroy');
    Route::post('sales/upload-import', [SalesOrderController::class, 'uploadImport'])->name('sales.upload.import');
    Route::post('sales/execute-import', [SalesOrderController::class, 'executeImport'])->name('sales.execute.import');
    
    Route::resource('products', ProductController::class);
    Route::post('producsts/stock-card', [ProductController::class, 'stockCard'])->name('products.stock-card');
    
});

Route::get('/send', function () {
    broadcast(new App\Events\EveryoneEvent());
    return response('Sent');
});

Route::get('/receiver', function () {
    return view('receiver');
});

require __DIR__.'/auth.php';

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\EccompProduct;
use App\Http\Requests\Product\StoreProductRequest;
use App\Http\Requests\Product\UpdateProductRequest;
use Illuminate\Support\Facades\DB;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = EccompProduct::orderBy('id', 'desc')->get();
        return view('product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = EccompProduct::CATEGORIES;
        return view('product.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreProductRequest $request)
    {
        $product = EccompProduct::create([
            'name' => $request->nama_produk,
            'code' => $request->kode_produk,
            'purchase_price' => $request->harga_beli,
            'sell_price' => $request->harga_jual,
            'category' => $request->kategori,
        ]);
        return redirect()->route('products.index')->with('success', 'Produk berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($code)
    {
        $product = EccompProduct::where('code', $code)->firstOrFail();
        $product->price_formated = number_format($product->sell_price, 0, ',', '.');
        
        return response()->json($product);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = EccompProduct::findOrFail($id);
        $categories = EccompProduct::CATEGORIES;
        return view('product.edit', compact('product', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateProductRequest $request, $id)
    {
        $product = EccompProduct::whereId($id)->update([
            'name' => $request->nama_produk,
            'code' => $request->kode_produk,
            'purchase_price' => $request->harga_beli,
            'sell_price' => $request->harga_jual,
            'category' => $request->kategori,
        ]);
        return redirect()->route('products.index')->with('success', 'Edit produk berhasil');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * Report stock card
     *
     * @return void
     */
    public function stockCard(Request $request)
    {
        $stockCard = DB::table('eccomp_report_logs')
            ->where('eccomp_product_code', $request->product_code)
            ->get();
        
        $dateStockCard = $stockCard->unique('date_transaction')->pluck('date_transaction');
        $newStockCard = [];
        $totalStock = 0;
        foreach ($dateStockCard as $date) {
            $newStockCard[$date] = [
                'total_pembelian' => 0,
                'total_penjualan' => 0,
                'stock' => $totalStock
            ];
            $stocks = $stockCard->where('date_transaction', $date);
            foreach ($stocks as $stock) {
                if ($stock->type == 'pembelian') {
                    $totalStock += $stock->qty; 
                    $newStockCard[$date]['total_pembelian'] = $newStockCard[$date]['total_pembelian'] + $stock->qty;
                    $newStockCard[$date]['stock'] = $totalStock;
                }else {
                    $totalStock -= $stock->qty; 
                    $newStockCard[$date]['total_penjualan'] = $newStockCard[$date]['total_penjualan'] + $stock->qty;
                    $newStockCard[$date]['stock'] = $totalStock;
                }
            }
        }
        return response()->json($newStockCard);
    }
}

resources/views/product/create.blade.php
@extends('app')
@section('content')
<div class="container">
    <div class="card">
        <div class="card-header">
            Tambah Produk
        </div>
        <div class="card-body">
            <form method="POST" action="{{ route('products.store') }}">
                @csrf
                <div class="form-group">
                    <label>Nama Produk</label>
                    <input type="text" name="nama_produk" value="{{ old('nama_produk') }}"
                        class="form-control @error('nama_produk') is-invalid @enderror" placeholder="Nama Produk">
                    @error('nama_produk')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>
                <div class="form-group">
                    <label>Kode Produk</label>
                    <input type="text" name="kode_produk" value="{{ old('kode_produk') }}"
                        class="form-control @error('kode_produk') is-invalid @enderror"
                        placeholder="Kode Produk (unik)">
                    @error('kode_produk')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>
                <div class="form-group">
                    <label>Harga Beli</label>
                    <input type="text" name="harga_beli" value="{{ old('harga_beli') }}"
                        class="form-control purchase_price @error('harga_beli') is-invalid @enderror" placeholder="Harga Beli">
                    @error('harga_beli')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>
                <div class="form-group">
                    <label>Harga Jual</label>
                    <input type="text" name="harga_jual" value="{{ old('harga_jual') }}"
                        class="form-control sell_price @error('harga_jual') is-invalid @enderror" placeholder="Harga Jual">
                    @error('harga_jual')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>
                <div class="form-group">
                    <label>Kategori</label>
                    <select name="kategori" class="form-control @error('kategori') is-invalid @enderror">
                        @foreach ($categories as $category)
                        <option value="{{ $category }}" {{ old('kategori') == $category ? 'selected' : '' }}>
                            {{ $category }}
                        </option>
                        @endforeach
                    </select>
                    @error('kategori')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection
@section('script')
    <script src="https://cdn.jsdelivr.net/npm/autonumeric@4.1.0"></script>
    <script>
        // The options are...optional :)
        const autoNumericOptions = {
            digitGroupSeparator : '.',
            decimalCharacter : ',',
            decimalCharacterAlternative: '.',
            unformatOnSubmit: true
        };
        
        // Initialization
        new AutoNumeric('.purchase_price', autoNumericOptions);
        new AutoNumeric('.sell_price', autoNumericOptions);
    </script>
@endsection

resources/views/product/edit.blade.php
@extends('app')
@section('content')
<div class="container">
    <div class="card">
        <div class="card-header">
            Edit Produk
        </div>
        <div class="card-body">
            <form method="POST" action="{{ route('products.update', $product->id) }}">
                @method('PUT')
                @csrf
                <div class="form-group">
                    <label>Nama Produk</label>
                    <input type="text" name="nama_produk" value="{{ $product->name }}"
                        class="form-control @error('nama_produk') is-invalid @enderror" placeholder="Nama Produk">
                    @error('nama_produk')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>
                <div class="form-group">
                    <label>Kode Produk</label>
                    <input type="text" name="kode_produk" value="{{ $product->code }}"
                        class="form-control @error('kode_produk') is-invalid @enderror"
                        placeholder="Kode Produk (unik)">
                    @error('kode_produk')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>
                <div class="form-group">
                    <label>Harga Beli</label>
                    <input type="text" name="harga_beli" value="{{ $product->purchase_price }}"
                        class="form-control purchase_price @error('harga_beli') is-invalid @enderror"
                        placeholder="Harga Beli">
                    @error('harga_beli')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>
                <div class="form-group">
                    <label>Harga Jual</label>
                    <input type="text" name="harga_jual" value="{{ $product->sell_price }}"
                        class="form-control sell_price @error('harga_jual') is-invalid @enderror"
                        placeholder="Harga Jual">
                    @error('harga_jual')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>
                <div class="form-group">
                    <label>Kategori</label>
                    <select name="kategori" class="form-control @error('kategori') is-invalid @enderror">
                        @foreach ($categories as $category)
                        <option value="{{ $category }}" {{ $product->category == $category ? 'selected' : '' }}>
                            {{ $category }}
                        </option>
                        @endforeach
                    </select>
                    @error('kategori')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection
@section('script')
<script src="https://cdn.jsdelivr.net/npm/autonumeric@4.1.0"></script>
<script>
    // The options are...optional :)
        const autoNumericOptions = {
            digitGroupSeparator : '.',
            decimalCharacter : ',',
            decimalCharacterAlternative: '.',
            unformatOnSubmit: true
        };
        
        // Initialization
        new AutoNumeric('.purchase_price', autoNumericOptions);
        new AutoNumeric('.sell_price', autoNumericOptions);
</script>
@endsection

resources/views/product/index.blade.php
@extends('app')
@section('css')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap4.min.css">
@endsection
@section('content')
    <div class="container">
        @if (session('success'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ session('success') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        @endif
        <div class="card">
            <div class="card-header">
                Data Produk
                <a href="{{ route('products.create') }}" class="btn btn-primary float-right">Tambah Produk</a>
            </div>
            <div class="card-body">
                <table id="product" class="table table-striped table-bordered" style="width:100%">
                    <thead>
                        <tr>
                            <th>Product</th>
                            <th>Kode Produk</th>
                            <th>Harga Beli</th>
                            <th>Harga Jual</th>
                            <th>Stok</th>
                            <th>Kategori</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                       @foreach ($products as $product)
                           <tr>
                               <td>{{ $product->name }}</td>
                               <td>{{ $product->code }}</td>
                               <td>{{ number_format($product->purchase_price, 2, ',', '.') }}</td>
                               <td>{{ number_format($product->sell_price, 2, ',', '.') }}</td>
                               <td>{{ $product->stock }}</td>
                               <td>{{ $product->category }}</td>
                               <th>
                                    <a href="{{ route('products.edit', $product->id) }}" class="btn-btn-warning btn-xs">
                                        <span class="fas fa-edit"></span>
                                    </a>
                               </th>
                           </tr>
                       @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#product').DataTable({
                ordering: false
            });
        } );
    </script>
@endsection