routes/web.php
<?php

use App\Http\Controllers\LogsController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\SalesOrderController;
use App\Http\Controllers\PurchaseOrderController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::prefix('dashboard')->middleware('auth:web')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard.index');
    Route::get('dailychart', [DashboardController::class, 'dailyChart'])->name('dashboard.chart.daily');
    Route::get('prosentasechart', [DashboardController::class, 'prosentaseChart'])->name('dashboard.chart.prosentase');
    Route::get('lastsixmonth', [DashboardController::class, 'sixMonthChartTransaction'])->name('dashboard.chart.sixmonth');
    Route::get('logs', [LogsController::class, 'index'])->name('logs.index');
    Route::get('/report/profit', [ReportController::class, 'profit'])->name('report.profit');
    Route::get('/report/stockcard', [ReportController::class, 'stockCard'])->name('report.stock-card');
    Route::get('/report/transaction', [ReportController::class, 'transaction'])->name('report.transaction');

    Route::resource('purchases', PurchaseOrderController::class)->except(['destroy']);
    Route::delete('purchases/destroy', [PurchaseOrderController::class, 'destroy'])->name('purchases.destroy');
    Route::post('purchase/upload-import', [PurchaseOrderController::class, 'uploadImport'])->name('purchases.upload.import');
    Route::post('purchase/execute-import', [PurchaseOrderController::class, 'executeImport'])->name('purchases.execute.import');
    
    Route::resource('sales', SalesOrderController::class)->except(['destroy']);
    Route::delete('sales/destroy', [SalesOrderController::class, 'destroy'])->name('sales.destroy');
    Route::post('sales/upload-import', [SalesOrderController::class, 'uploadImport'])->name('sales.upload.import');
    Route::post('sales/execute-import', [SalesOrderController::class, 'executeImport'])->name('sales.execute.import');
    
    Route::resource('products', ProductController::class);
    Route::post('producsts/stock-card', [ProductController::class, 'stockCard'])->name('products.stock-card');
    
});

Route::get('/send', function () {
    broadcast(new App\Events\EveryoneEvent());
    return response('Sent');
});

Route::get('/receiver', function () {
    return view('receiver');
});

require __DIR__.'/auth.php';

resources/views/sales/create.blade.php
@extends('app')
@section('css')
<link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css"
    integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw=="
    crossorigin="anonymous" />
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/@ttskch/select2-bootstrap4-theme@x.x.x/dist/select2-bootstrap4.min.css">
@endsection
@section('content')
<div class="container">
    @if (session('error'))
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ session('error') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    @endif
    @if ($errors->any())
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ $errors->first() }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    @endif
    <div class="card">
        <div class="card-header">
            <h4>Tambah Transaksi Penjualan</h4>
        </div>
        <div class="card-body">
            <form action="{{ route('sales.store') }}" method="POST">
                @csrf
                <div class="form-group">
                    <label>Tanggal</label>
                    <input autocomplete="off" type="text" class="form-control datepicker @error('tanggal') is-invalid @enderror"
                        name="tanggal">
                    @error('tanggal')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>
                <div class="form-group">
                    <label>Customer</label>
                    <select name="customer" class="form-control select2 @error('customer') is-invalid @enderror">
                        <option value="">Pilih Customer</option>
                        @foreach ($customers as $customer)
                            <option value="{{ $customer->id }}">{{ $customer->name }}</option>
                        @endforeach
                    </select>
                    @error('customer')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>
                <div class="form-group">
                    <button type="button" onclick="addProduct()" class="btn btn-primary">
                        <span class="fa fa-plus"></span>
                        Tambah Produk
                    </button>
                </div>

                <div id="product">
                </div>
                <div class="form-group" id="total">
                    <div class="row">
                        <div class="col-md-10"></div>
                        <div class="col-md-2" id="total"></div>
                    </div>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary d-none save">
                        <span class="fa fa-save"></span>
                        Simpan
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection
@section('script')
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"
    integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ=="
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/autonumeric@4.1.0"></script>
<script>
    var counter = 1;
            $(".datepicker").datepicker({
                autoclose: true,
                todayHighlight: true
            })
            $(".select2").select2({
                theme: 'bootstrap4'
            })

        function addProduct() {
            $("#product").append(`<div class="form-row">
                <div class="form-group col-md-4">
                    <label for="inputCity">Produk</label>
                    <select class="form-control select2" required name="produk[]" onchange="setProduct(`+counter+`)" id="product`+counter+`">
                        <option>Pilih produk</option>
                        @foreach($products as $product)
                            <option value="{{ $product->code }}" >{{ $product->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group col-md-2">
                    <label for="inputState">Stock</label>
                    <input type="text" id="max_qty`+counter+`" class="form-control" readonly>
                </div>
                <div class="form-group col-md-1">
                    <label for="inputState">QTY</label>
                    <input type="number" value="1" required id="qty`+counter+`" onkeyup="changeQty(`+counter+`)" name="qty[]" class="form-control">
                </div>
                <div class="form-group col-md-1">
                    <label>Diskon(%)</label>
                    <input type="number" value="0" required id="discount`+counter+`" onkeyup="addDiscount(`+counter+`)" name="discount[]" class="form-control">
                </div>
                <div class="form-group col-md-3">
                    <label for="inputZip">Total Price</label>
                    <input type="text" id="money`+counter+`" name="price[]" readonly class="form-control">
                </div>
                <input type="hidden" id="price`+counter+`">
                <div class="form-group col-md-1">
                    <span class="fa fa-trash pt-5 pl-2 removerow"></span>
                </div>
            </div>`);

            $(".select2").select2({
                theme: 'bootstrap4'
            });
            counter++

            if (counter > 1) {
                $(".save").removeClass('d-none')
            }

        }

        function setProduct(number) {
            let product = $("#product"+number).val()
            if (product != '') {
                $.get("{{ route('dashboard.index') }}/products/"+product)
                .done(function( data ) {
                    let qty = $("#qty"+number).val()
                    if (isNaN(qty) || qty == '' || parseInt(qty) < 1) { qty=0 }
                    $("#money"+number).val(formatRupiah(parseInt(data.sell_price) *parseInt(qty)))
                    $("#price"+number).val(data.sell_price)
                    $("#max_qty"+number).val(data.stock)
                    calculateTotal()
                });
            }
        }

        function changeQty(number) {
            let qty = $("#qty"+number).val()
            let stock = $("#max_qty"+number).val()
            let discount = $("#discount"+number).val()
            
            if (qty > stock) {
               $("#qty"+number).val(0)
            }
            
            let price = $("#price"+number).val();
            
            if (isNaN(qty) || qty == '' || parseInt(qty) < 1) {
                qty = 0
            }

            if (price == '') {
                price = 0
            }           

            if (discount == '') {
                discount = 0
            }           

            let total = parseInt(price) * parseInt(qty)
            let discountTotal = (parseInt(discount) / 100) * total

            $("#money"+number).val(formatRupiah(total-discountTotal))
            calculateTotal()
        }

        function addDiscount(number) {
            let qty = $("#qty"+number).val()
            let price = $("#price"+number).val();
            let discount = $("#discount"+number).val()

            if (discount > 100) {
                $("#discount"+number).val(100)
            }
            
            if (isNaN(qty) || qty == '' || parseInt(qty) < 1) {
                qty = 0
            }

            if (price == '') {
                price = 0
            }           
            if (discount == '') {
                discount = 0
            }           

            let total = parseInt(price) * parseInt(qty)
            let discountTotal = (parseInt(discount) / 100) * total

            $("#money"+number).val(formatRupiah(total-discountTotal))
            calculateTotal()
        }

        function formatRupiah(angka){
			return new Intl.NumberFormat("id-ID", {  currency: "IDR" }).format(angka);
		}

        function calculateTotal(){
            var values = $("input[name='price[]']")
              .map(function(){
                  return parseInt($(this).val().replace(/\./g,''))
                }).get()
            let totalPrice = values.reduce((a, b) => a + b, 0)
            $("#total").html("Total Price : "+formatRupiah(totalPrice))
        }

        $("#product").on("click", ".removerow", function () {
            $(this).closest('.form-row').remove();
            counter--

            if (counter == 1) {
                $(".save").addClass('d-none')
            }
        });
        
</script>
@endsection

resources/views/sales/edit.blade.php
@extends('app')
@section('css')
<link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css"
    integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw=="
    crossorigin="anonymous" />
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/@ttskch/select2-bootstrap4-theme@x.x.x/dist/select2-bootstrap4.min.css">
@endsection
@section('content')
<div class="container">
    @if (session('error'))
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ session('error') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    @endif
    <div class="card">
        <div class="card-header">
            <h4>Edit Transaksi Penjualan</h4>
        </div>
        <div class="card-body">
            <form action="{{ route('sales.update', $transaction->id) }}" method="POST">
                @method('PUT')
                @csrf
                <div class="form-group">
                    <label>Tanggal</label>
                    <input autocomplete="off" type="text"
                        class="form-control datepicker @error('tanggal') is-invalid @enderror" name="tanggal">
                    @error('tanggal')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>
                <div class="form-group">
                    <label>Customer</label>
                    <select name="customer" class="form-control select2 @error('customer') is-invalid @enderror">
                        <option value="">Pilih Customer</option>
                        @foreach ($customers as $customer)
                            <option value="{{ $customer->id }}"
                                {{ $customer->id == $transaction->eccomp_customer_id ? 'selected' : '' }}>{{ $customer->name }}</option>
                        @endforeach
                    </select>
                    @error('customer')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>
                <div class="form-group">
                    <button type="button" onclick="addProduct()" class="btn btn-primary">
                        <span class="fa fa-plus"></span>
                        Tambah Produk
                    </button>
                </div>

                <div id="product">
                    @foreach ($transaction->eccompTransactionDetail as $key => $item)
                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label for="inputCity">Produk</label>
                                <select class="form-control select2" required name="produk[]" onchange="setProduct({{ $key+1 }})"
                                    id="product{{ $key+1 }}">
                                    <option>Pilih produk</option>
                                    @foreach($products as $product)
                                    <option value="{{ $product->code }}" 
                                        {{ $product->code == $item->eccomp_product_code ? 'selected' : '' }}>{{ $product->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group col-md-2">
                                <label for="inputState">Stock</label>
                                <input type="text" id="max_qty{{ $key+1 }}" class="form-control" value="{{ $item->product->stock - $item->qty }}" readonly>
                            </div>
                            <div class="form-group col-md-2">
                                <label for="inputState">QTY</label>
                                <input type="number" value="1" required id="qty{{ $key+1 }}" value="{{ $item->qty }}" onkeyup="changeQty({{ $key+1 }})" name="qty[]"
                                    class="form-control">
                            </div>
                            <div class="form-group col-md-3">
                                <label for="inputZip">Price</label>
                                <input type="text" id="money{{ $key+1 }}" name="price[]" readonly class="form-control" value="{{ number_format($item->total_price, 0, ',', '.') }}">
                            </div>
                            <input type="hidden" value="{{ $item->product->sell_price }}" id="price{{ $key+1 }}">
                            <div class="form-group col-md-1">
                                <span class="fa fa-trash pt-5 pl-2 removerow"></span>
                            </div>
                        </div>
                    @endforeach
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary save">
                        <span class="fa fa-save"></span>
                        Simpan
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection
@section('script')
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"
    integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ=="
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/autonumeric@4.1.0"></script>
<script>
    var counter = {{ $transaction->eccompTransactionDetail->count()+1 }};
            $(".datepicker").datepicker({
                autoclose: true,
                todayHighlight: true
            })
            $('.datepicker').datepicker('update', "{{ \Carbon\Carbon::parse($transaction->date)->format('d/m/Y') }}");

            $(".select2").select2({
                theme: 'bootstrap4'
            })

        function addProduct() {
            $("#product").append(`<div class="form-row">
                <div class="form-group col-md-4">
                    <label for="inputCity">Produk</label>
                    <select class="form-control select2" required name="produk[]" onchange="setProduct(`+counter+`)" id="product`+counter+`">
                        <option>Pilih produk</option>
                        @foreach($products as $product)
                            <option value="{{ $product->code }}" >{{ $product->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group col-md-2">
                    <label for="inputState">Stock</label>
                    <input type="text" id="max_qty`+counter+`" class="form-control" readonly>
                </div>
                <div class="form-group col-md-2">
                    <label for="inputState">QTY</label>
                    <input type="number" value="1" required id="qty`+counter+`" onkeyup="changeQty(`+counter+`)" name="qty[]" class="form-control">
                </div>
                <div class="form-group col-md-3">
                    <label for="inputZip">Price</label>
                    <input type="text" id="money`+counter+`" name="price[]" readonly class="form-control">
                </div>
                <input type="hidden" id="price`+counter+`">
                <div class="form-group col-md-1">
                    <span class="fa fa-trash pt-5 pl-2 removerow"></span>
                </div>
            </div>`);

            $(".select2").select2({
                theme: 'bootstrap4'
            });
            counter++

            if (counter > 1) {
                $(".save").removeClass('d-none')
            }

        }

        function setProduct(number) {
            let product = $("#product"+number).val()
            if (product != '') {
                $.get("{{ route('dashboard.index') }}/products/"+product)
                .done(function( data ) {
                    $("#money"+number).val(data.price_formated)
                    $("#price"+number).val(data.sell_price)
                    $("#max_qty"+number).val(data.stock)
                    console
                });
            }
        }

        function changeQty(number) {
            let qty = $("#qty"+number).val()
            let stock = $("#max_qty"+number).val()
            if (qty < 1  ) {
               $("#qty"+number).val(1)
            }

            if (qty > stock) {
               $("#qty"+number).val(stock)
            }
            
            let price = $("#price"+number).val()

            if (isNaN(qty) || qty == '') {
                qty = 1
            }

            let total = parseInt(price) * parseInt(qty)
            $("#money"+number).val(formatRupiah(total))
        }

        function formatRupiah(angka){
			return new Intl.NumberFormat("id-ID", {  currency: "IDR" }).format(angka);
		}

        $("#product").on("click", ".removerow", function () {
            $(this).closest('.form-row').remove();
            counter--

            if (counter == 1) {
                $(".save").addClass('d-none')
            }
        });
        
</script>
@endsection

resources/views/sales/show.blade.php
@extends('app')

@section('content')
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h4>Detail Transaksi</h4>
            </div>
            <div class="card-body">
                <table class="table table-bordered">
                    <tr>
                        <td>Tanggal</td>
                        <td>{{ \Carbon\Carbon::parse($transaction->date)->format('d/m/Y') }}</td>
                    </tr>
                    <tr>
                        <td>Customer</td>
                        <td>{{ $transaction->customer->name }}</td>
                    </tr>
                    <tr>
                        <td>Admin</td>
                        <td>{{ $transaction->author->name }}</td>
                    </tr>
                </table>
                <table class="table table-bordered">
                    <thead>
                        <th>Produk</th>
                        <th>Qty</th>
                        <th>Harga</th>
                        <th>Total</th>
                    </thead>
                    <tbody>
                        @foreach ($transaction->eccompTransactionDetail as $item)
                            <tr>
                                <td>{{ $item->product->name }}</td>
                                <td>{{ $item->qty }}</td>
                                <td>{{ number_format($item->product->sell_price, 2, ',', '.') }}</td>
                                <td>{{ number_format($item->total_price, 2, ',', '.') }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection